# - Try to find the LIBLUA config processing library
# Once done this will define
#
# LIBLUA_FOUND - System has LIBLUA
# LIBLUA_INCLUDE_DIR - the LIBLUA include directory
# LIBLUA_LIBRARIES 0 The libraries needed to use LIBLUA

FIND_PATH(LIBLUA_INCLUDE_DIR NAMES lua.h)
FIND_LIBRARY(LIBLUA_LIBRARY NAMES lua PATH /usr/lib /usr/local/lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBLUA DEFAULT_MSG LIBLUA_LIBRARY LIBLUA_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBLUA_INCLUDE_DIR LIBLUA_LIBRARY)
