# - Try to find the LIBHIREDIS config processing library
# Once done this will define
#
# LIBHIREDIS_FOUND - System has LIBHIREDIS
# LIBHIREDIS_INCLUDE_DIR - the LIBHIREDIS include directory
# LIBHIREDIS_LIBRARIES 0 The libraries needed to use LIBHIREDIS

FIND_PATH(LIBHIREDIS_INCLUDE_DIR NAMES hiredis/hiredis.h)
FIND_LIBRARY(LIBHIREDIS_LIBRARY NAMES hiredis PATH /usr/lib /usr/local/lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBHIREDIS DEFAULT_MSG LIBHIREDIS_LIBRARY LIBHIREDIS_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBHIREDIS_INCLUDE_DIR LIBHIREDIS_LIBRARY)
